services:
  postgres:
    ports: !reset []

  backend:
    volumes: !reset []

  frontend:
    depends_on:
      backend:
        condition: service_started

  nginx:
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_started
    ports:
      - "443:443"
    volumes:
      - /opt/student-registration/acme-challenge:/var/www/certbot:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
